//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishTyping.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnglishTyping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 2
        ///1080
        ///&amp;c
        ///10-point
        ///10th
        ///11-point
        ///12-point
        ///16-point
        ///18-point
        ///1st
        ///2,4,5-t
        ///2,4-d
        ///20-point
        ///2D
        ///2nd
        ///30-30
        ///3D
        ///3-D
        ///3M
        ///3rd
        ///48-point
        ///4-D
        ///4GL
        ///4H
        ///4th
        ///5-point
        ///5-T
        ///5th
        ///6-point
        ///6th
        ///7-point
        ///7th
        ///8-point
        ///8th
        ///9-point
        ///9th
        ///a
        ///a&apos;
        ///a-
        ///A&amp;M
        ///A&amp;P
        ///A.
        ///A.A.A.
        ///A.B.
        ///A.B.A.
        ///A.C.
        ///A.D.
        ///A.D.C.
        ///A.F.
        ///A.F.A.M.
        ///A.G.
        ///A.H.
        ///A.I.
        ///A.I.A.
        ///A.I.D.
        ///A.L.
        ///A.L.P.
        ///A.M.
        ///A.M.A.
        ///A.M.D.G.
        ///A.N.
        ///a.p.
        ///a.r.
        ///A.R.C.S.
        ///A.U.
        ///A.U.C.
        ///A.V.
        ///a.w.
        ///A.W.O.L.
        ///A/C
        ///A/F
        ///A/O
        ///A/P
        ///A/V
        ///A1
        ///A-1
        ///A4
        ///A5
        ///AA
        ///AAA
        ///AAAA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
